###
GET http://localhost:3000

###
GET http://localhost:3000/user

###
GET http://localhost:3000/user/42

###
POST http://localhost:3000/user
content-type: application/json

{
    "userName": "user9",
    "email"   : "user9@gmail.com",
    "hashPwd" : "123",
    "role"    : "users"
}

###
POST http://localhost:3000/user/create
content-type: application/json

{
    "userName": "delete",
    "email"   : "delete@gmail.com",
    "hashPwd" : "123",
    "role"    : "delete"
}

###
PATCH http://localhost:3000/user/2
content-type: application/json

{
    "userName": "agung",
    "role"    : "agung"
}

###
DELETE http://localhost:3000/user/8

###
DELETE http://localhost:3000/user/8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQyLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcxMDQ4NDkzOCwiZXhwIjoxNzEwODMwNTM4fQ._QpWsrmZEnNfH8FGn6ipAw4m3XcwoJgHTQqQYimZExc


###
POST http://localhost:3000/auth/login
content-type: application/json

{
    "email"   : "admin@gmail.com",
    "hashPwd" : "123"
}

### ini karena bukan user rolenya admin / user tidak bisa akses
GET http://localhost:3000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQ0LCJlbWFpbCI6Imd1ZXN0QGdtYWlsLmNvbSIsInJvbGUiOiJndWVzdCIsImlhdCI6MTcxMDM4MzgzMCwiZXhwIjoxNzEwNzI5NDMwfQ.LFE8gCJKuEzcT49-LxKIrVddcid9s6usYvAhXC8abrc

### ini user rolenya admin
GET http://localhost:3000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQyLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcxMDM4Mzc5MywiZXhwIjoxNzEwNzI5MzkzfQ.uY1qxZgJlVeR6-wnICGxIW1mKnwRT4twtJ7FRYBEQXA